tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "asdf"
brew "aws-iam-authenticator"
brew "awscli"
brew "bash-completion"
brew "coreutils"
brew "direnv"
brew "docker-completion"
brew "docker-compose-completion"
brew "dockutil"
brew "doctl"
brew "fish"
brew "fzf"
brew "git"
brew "gnu-getopt"
brew "gnu-sed"
brew "gnupg"
brew "helm"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "mint"
brew "mkcert"
brew "nss"
brew "pgcli"
brew "postgresql"
brew "sops"
brew "stow"
brew "swiftlint"
brew "terraform"
brew "the_silver_searcher"
brew "thefuck"
brew "vim"
brew "watchman"
cask "android-studio"
cask "appcleaner"
cask "datagrip"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "google-cloud-sdk"
cask "insomnia"
cask "iterm2"
cask "karabiner-elements"
cask "postman"
cask "react-native-debugger"
cask "rocket"
cask "sf-symbols"
cask "shimo"
cask "visual-studio-code"
cask "wireshark"
cask "adoptopenjdk/openjdk/adoptopenjdk8"
mas "1Password 7", id: 1333542190
mas "AdGuard for Safari", id: 1440147259
mas "Bear", id: 1091189122
mas "DaisyDisk", id: 411643860
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Magnet", id: 441258766
mas "Next Meeting", id: 1017470484
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Save to Pocket", id: 1477385213
mas "Slack", id: 803453959
mas "ToothFairy", id: 1191449274
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
