#!/bin/bash

code --list-extensions > $DOTFILES_HOME/vscode/extensions
brew bundle dump --force --no-restart --file=$DOTFILES_HOME/macOS/Brewfile

cp $HOME/.local/share/fish/fish_history $DOTFILES_HOME/_backup/
echo "iTerm Profiles > Other Actions... > Save Profile as JSON..."
