#!/bin/bash

CYAN='\033[0;36m'
NC='\033[0m' # No Color

function print() {
  echo -e "${CYAN}==> $1${NC}"
}

# https://stackoverflow.com/questions/3497123/run-git-pull-over-all-subdirectories
for i in */.git; do (
  print $(dirname "$i");

  git -C $i/.. remote show origin > /dev/null 2>&1
  remote_status=$?

  if [ $remote_status -ne 0 ]; then
    echo 'No remote'
    exit 1
  fi

  git -C $i/.. delete-branches
); done
