#!/bin/bash

CYAN='\033[0;36m'
NC='\033[0m' # No Color

function print() {
  echo -e "${CYAN}==> $1${NC}"
}

# https://stackoverflow.com/questions/3497123/run-git-pull-over-all-subdirectories
for i in */.git; do (
  print $(dirname "$i");
  cd $i/..
  git wipe
); done
