#!/bin/bash

git checkout -q master && git pull

# delete merged branches
git branch --merged | grep -v "\\*" | xargs -n 1 git branch -d

# delete squashed branches
# https://github.com/not-an-aardvark/git-delete-squashed
git for-each-ref refs/heads/ "--format=%(refname:short)" | while read branch; do mergeBase=$(git merge-base master $branch) &&
  [[ $(git cherry master $(git commit-tree $(git rev-parse $branch^{tree}) -p $mergeBase -m _)) == "-"* ]] &&
  git branch -D $branch; done

git remote prune origin
