#!/bin/bash

# https://superuser.com/questions/618501/changing-an-applications-icon-from-the-terminal-osx

cp $DOTFILES_HOME/icons/DataGrip.icns /Applications/DataGrip.app/Contents/Resources/datagrip.icns
touch /Applications/DataGrip.app

cp $DOTFILES_HOME/icons/Firefox.icns /Applications/Firefox.app/Contents/Resources/firefox.icns
touch /Applications/Firefox.app

cp $DOTFILES_HOME/icons/Insomnia.icns /Applications/Insomnia.app/Contents/Resources/Insomnia.icns
touch /Applications/Insomnia.app

# cp $DOTFILES_HOME/icons/Poolside_FM.icns /Applications/Poolside\ FM.app/Contents/Resources/AppIcon.icns
# touch /Applications/Poolside\ FM.app

cp $DOTFILES_HOME/icons/Spotify.icns /Applications/Spotify.app/Contents/Resources/Icon.icns
touch /Applications/Spotify.app

# cp $DOTFILES_HOME/icons/WhatsApp.icns /Applications/WhatsApp.app/Contents/Resources/electron.icns
# touch /Applications/WhatsApp.app

sudo killall Finder && sudo killall Dock
